### PR TITLE
MODORDERS-178/179 Increased flexibility in inventory integration

### PR DESCRIPTION
**Pull request by grabsefx**
https://issues.folio.org/browse/MODORDERS-178
https://issues.folio.org/browse/MODORDERS-179
## Purpose
* Add API tests for the stories MODORDERS-178 and MODORDERS-179
## Approach 
* Adding requests for testing various `createInventory` values (not specified, "None", "Instance", etc. )
* Adding cleanup for "createInventory" tests.
* Fixing validation scripts according to updated business logic.

Tests successfully passed on testing environment
image

### CODE REVIEW

**Comment by craigmcnally** [comment]
It's possible I'm missing something but I don't see where MODORDERS-179 is being exercised here... 

I was expecting to see something like:
* save the current config values
* set the config (create-inventory) to something different than the system defaults
* test that the appropriate inventory records are created for one or more of the order types as specified by the tenant's config
* remove the tenant config entirely
* test that the appropriate inventory records are being created for one or more of the order types as specified by the system defaults
* revert to the original tenant configuration

**Comment by grabsefx** [comment]
Folder `Test createInventory defaults` contains requests for testing system default values and mod-configuration default values. Pre-request scripts contain cleaning up of `createInventory` config and creating `createInventory` config with new values. In the end of the API tests original configs restored by request from folder `Cleanup-> Revert configs`
image

**Comment by grabsefx** [comment]
All tests passed successfully on testing environment

image

**Comment by piotr-kalashuk** [comment]
The API tests works fine when testing backend is used:

image

**Pull request merged**
