### PR TITLE
MODORGS-6 Add api tests for addresses

### PR DESCRIPTION
**Pull request by RamanAsadchy**
Positive tests :

- New tests : 
image

- Runner tests : 

image
image
image

### CODE REVIEW

**Comment by javalkar-varun** [comment]
On running test in `folio-testing-okapi.aws.indexdata.com`, few tests are failing
image

**Comment by piotr-kalashuk** [comment]
Once I created a few more addresses the API test starts failing:
image

**Comment by javalkar-varun** [comment]
I'm running tests against config:
image

They are still failing as before
image
I think we should be able to run tests against the existing environment as is.

**Comment by RamanAsadchy** [comment]
Passed API tests on folio/testing :
image

**Comment by javalkar-varun** [comment]
All tests pass for me in folio/testing local vagrant box. However, this check fails in existing code in master in `folio-testing-okapi.aws.indexdata.com` env:
`pm.expect(organizations).to.have.lengthOf(1);` I think we should not check for the specific count because there might be an existing organization. So, instead, we could check for a length greater than 1.
image
Other than that, looks good.

**Comment by javalkar-varun** [comment]
All tests pass now in both local vagrant box and `folio-testing-okapi.aws.indexdata.com`
image

**Pull request merged**
