### PR TITLE
Mdexp 62&63 create project for api test + api tests for endpoints listed in mdexp-63

### PR DESCRIPTION
**Pull request by IlliaDaliek**
**PURPOSE:**
* Setup project for API tests
* Add API tests for
 _/data-export/fileDefinitions_
 _/data-export/fileDefinitions/{fileDefinitionID}/upload_

**DEFAULT VALUES**
For testing purposes there have been added a set of default data:
1. **default test tenant data.**
2. **default enabled modules:**
- mod-users
- mod-login
- mod-permissions 
- mod-data-export (requires mod-source-record-storage)
- mod-source-record-storage (requires mod-pubsub)
- mod-pubsub
3. **default user data**
- test admin user data;
- reqular user data.
4. **default user credentials:**
- diku_admin user creds.
- testAdmin user creds
- regular user creds (has permissions to mod-data-export operations)
5. **default list of regular user permissions:**
- data-export.export.post;
- data-export.file-definitions.item.get;
- data-export.file-definitions.item.post;
- data-export.file-definitions.upload.post;
- data-export.job-executions.items.get.
6. **Test file data:**
- fileName of test file definition json.

**ENVIRONMENT VARIABLES**
- testTenant name;
- protocol;
- url;
- okapiport;
- xokapitenant;
- resourcesUrl by which it is possible to download the test file for uploading.

### CODE REVIEW

**Comment by VictorSoroka1** [comment]
As I remember the indentation should be addressed.

**Comment by Igor-Gorchakov** [comment]
* Drop mod-configuration
* Beautify  json file - use https://jsonformatter.org/ with 2 tab spaces, press Format/Beautify

**Comment by IlliaDaliek** [comment]
Within the black lines scope are placed the API test results by itself. Other requests are just environment configuration requests for main API tests listed in MDEXP-63 and further API tests that will be added in future as well.
API tests result

**Comment by Igor-Gorchakov** [comment]
@KVupp  @mrdpopov  waiting for your review

**Pull request merged**
