### PR TITLE
API tests for MODORDERS-340

### PR DESCRIPTION
**Pull request by javalkar-varun**
**Purpose:**
API test for https://issues.folio.org/browse/MODORDERS-340

**Approach:**
- Update test data with call number
- During `check-in` and `receive`, verify that `itemLevelCallNumber` exists in an item in inventory

**Verify:**
folio-snapshot:
Screen Shot 2019-12-20 at 11 35 31 AM

### CODE REVIEW

**Comment by craigmcnally** [comment]
Ugh, unfortunately I'm getting test failures when running against folio-testing.... I'm guessing this is because there have been changes since this was comitted 21 days ago.  Sorry it took so long to get to this @javalkar-varun .  Can you please take a look?

**Comment by javalkar-varun** [comment]
@craigmcnally It depends on https://issues.folio.org/browse/MODORDERS-350 
API tests need to be updated because there are changes to piece schema
Same is the case for https://github.com/folio-org/folio-api-tests/pull/351#issuecomment-572175168

**Comment by craigmcnally** [comment]
Darn.  Trying to figure out what the cleanest way to resolve this is...  I'll try to verify these changes manually and we can fix up the API tests next sprint.  Coordination will be needed with the PRs you mention above.

**Comment by javalkar-varun** [comment]
Sounds good. I think we should have them ready to merge by Monday if PRs for MODORDERS-350 are merged before that.

**Comment by javalkar-varun** [comment]
Verified in folio-snapshot:
image

**Comment by craigmcnally** [comment]
Successfully ran these on folio-testing:

image

**Pull request merged**
