### PR TITLE
Orders: make required inventory types configurable

### PR DESCRIPTION
**Pull request by piotr-kalashuk**
## Purpose
- [MODORDERS-239](https://issues.folio.org/browse/MODORDERS-239) Make `instance-type` configurable
- [MODORDERS-240](https://issues.folio.org/browse/MODORDERS-240) Make `instance-status` configurable
- [MODORDERS-241](https://issues.folio.org/browse/MODORDERS-241) Make `loan-type` configurable

### New collection variables
Variable | Initial Value | Description  
 --- | --- | --- 
`inventory-instanceTypeCode` | ordersApiTestsInstanceTypeCode | Inventory instance type code which is going to be used for instance creation when order transits to `Open` status
`inventory-instanceStatusCode` | ordersApiTestsInstanceStatusCode | Inventory instance status code which is going to be used for instance creation when order transits to `Open` status
`inventory-loanTypeName` | ordersApiTestsLoanTypeName | Inventory loan type name which is going to be used for item creation when order transits to `Open` status

The values above are used to create configs in mod-configuration

#### Setup
`Prepare inventory types` - Creating API Test specific inventory types:
   - Identifier Type
   - Instance Type
   - Instance Status
   - Loan Type
   - Material Type

image

#### Positive Tests
- `utils.preparePoLine` function is updated:
   - set test material type for E-resource and Physical objects (`poLine.eresource.materialType` and `poLine.physical.materialType`)
   - `poLine.details.productIds`: all product ids are unique and product type is `Vendor Title Number` to make sure that new instances are created for Open orders

image
- `utils.validateInstanceContent(instance, poLine)` function is added to validate that Instance type and status id's are test ones

image

- `utils.validateItemContent(item)` function is added to validate that `loanTypeId` and `materialTypeId` are test ones

image

- `Create Inventory` folder - all the configs are removed for tenant so system default values are used. After all requests completed, the test configs are restored

### CODE REVIEW

**Comment by craigmcnally** [comment]
Failures when run against folio-testing:
image

**Comment by piotr-kalashuk** [comment]
This failures are caused by `eb2d063a-5b4c-4cab-8db1-5fc5c5941df6` location id used in receiving body template
image
The API tests update was created prior to [MODORDERS-221](https://issues.folio.org/browse/MODORDERS-221) merged to master

**Comment by piotr-kalashuk** [comment]
Changed location id from receiving template to `fcd64ce1-6995-48f0-840e-89ffa2288371` (Main Library) which exists in Inventory reference data. The new location should be created for API tests as part of updates for [MODORDERS-221](https://issues.folio.org/browse/MODORDERS-221).

image

**Comment by craigmcnally** [comment]
Yup, looks better now:  
image

**Pull request merged**
