### PR TITLE
MODKBEKBJ-65 - API Tests POST /eholdings/packages endpoint

### PR DESCRIPTION
**Pull request by ivan-brovenko**
## Purpose
Per https://issues.folio.org/browse/MODKBEKBJ-65 we want to have API tests for POST `/eholdings/packages `endpoint
## Approach

- checked if tests from https://github.com/folio-org/folio-api-tests/blob/master/mod-kb-ebsco/mod-kb-ebsco.postman_collection.json pass for the endpoint in Java
-  added api tests to the mod-kb-ebsco-java postman collection

### CODE REVIEW

**Comment by sduvvuri-ebsco** [comment]
Overall this looks good but have a couple of questions - In folder 'packages' -> POST to package collection -> Positive -> there are 2 post requests to create 2 custom packages - If they are created exclusively to test delete endpoint, can we have them in "setup for packages test" folder instead?
Second question is regarding error messages for tests "with invalid contentType", "bad data for customCoverage", "package without name" and "package without content type" -> these error messages look different than what we get in Ruby?

**Comment by ivan-brovenko** [comment]
> Overall this looks good but have a couple of questions - In folder 'packages' -> POST to package collection -> Positive -> there are 2 post requests to create 2 custom packages - If they are created exclusively to test delete endpoint, can we have them in "setup for packages test" folder instead?
> Second question is regarding error messages for tests "with invalid contentType", "bad data for customCoverage", "package without name" and "package without content type" -> these error messages look different than what we get in Ruby?

One of post requests created to test deletion in put when "isSelected" property is false and the other to test deletion endpoint. Should we create one more post endpoint for positive case after putting these endpoints to "setup for packages test" folder? Error messages are different from ruby module because in json schema fields name and contentType are requeired and it handles before packagePostBodyValidator. If we make them not required the response would be like in the ruby module.
without_required

name_content_type

put_deletion

**Comment by carolegodfrey** [comment]
Agree on comment regarding error message differences - however that was discussed at sprint review as keeping as is for now. Tests worked fine for me on my local run -- also understand on having the Positive tests in `setup for packages test` -- it's a little odd not having any positive tests under the endpoint but probably better to call out for potential cleanup if needed (and not covered by DELETE or PUT)

**Comment by ivan-brovenko** [comment]
> Agree on comment regarding error message differences - however that was discussed at sprint review as keeping as is for now. Tests worked fine for me on my local run -- also understand on having the Positive tests in `setup for packages test` -- it's a little odd not having any positive tests under the endpoint but probably better to call out for potential cleanup if needed (and not covered by DELETE or PUT)

Thanks, updated

**Pull request merged**
